# ENV variables
OPENAI_API_KEY = "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"
FIREBASE_API_KEY = "AIzaSyD5ysQAC8VlFQQ7SPmIG6Wc73SGm2SXmCs"
FIREBASE_AUTH_DOMAIN = "adna-pro.firebaseapp.com"
FIREBASE_PROJECT_ID = "adna-pro"
FIREBASE_STORAGE_BUCKET = "adna-pro.firebasestorage.app"
FIREBASE_MESSAGING_SENDER_ID = "329870799600"
FIREBASE_APP_ID = "1:329870799600:web:6bd7777db4100269538835"
BACKEND_API_URL = "http://127.0.0.1:8000/generate"

# Firebase Admin SDK (converted from JSON)
[firebase_sdk]
type = "service_account"
project_id = "adna-pro"
private_key_id = "590b6037f913b8398e035fe9676bdc14dbe6a782"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCs/X9zDLeHvqCB
...
C2DK2M5FyJ/4yg==
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@adna-pro.iam.gserviceaccount.com"
client_id = "117088738300948521645"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40adna-pro.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

# Google Sheets Service Account (converted from JSON)
[gsheets]
type = "service_account"
project_id = "turnkey-science-465008-g5"
private_key_id = "a20f050299a901aac1f603a7bb78c152c83719c0"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCF4d8sIvQJgS4S
...
Xpt8WrsF
-----END PRIVATE KEY-----"""
client_email = "adna-io@turnkey-science-465008-g5.iam.gserviceaccount.com"
client_id = "112914073916532581612"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/adna-io%40turnkey-science-465008-g5.iam.gserviceaccount.com"
universe_domain = "googleapis.com"